# Composite action
name: "Setup repository and python dependecies"
description: "Checkout repo, install python and dependecies"

runs:

  using: "composite"
  steps:

    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Cache python dependecies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install python dependecies
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
      shell: bash
