name: build

on:
  [ "push", "pull_request" ]

jobs:

  build:

    name: build
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup python and dependecies using composite action
        uses: ./.github/actions

      - name: Check env vars
        run: echo "${HTTP_PROXY}"
        env:
          HTTP_PROXY: ${{ inputs.http_proxy }}
          HTTPS_PROXY: ${{ inputs.https_proxy }}
          PYTHON_DIR: ${{ inputs.python_dir }}

      - name: Build documentation
        run: sphinx-build -E -W -b html ./docs/source ./docs/build

      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: Sphinx documentation
          path: docs/build

  deploy:

    needs: build
    name: deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create branch for github pages
        run: |
          git fetch
          if git branch -r | grep "gh-pages$"
          then \
            git checkout gh-pages
          else \
            git checkout -b gh-pages
            git commit --allow-empty -m "Init gh-pages branch"
            git push origin gh-pages
          fi

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: Sphinx documentation
          path: docs

      - name: Create .nojekyll file
        run: echo > docs/.nojekyll

      - name: Commit artifacts
        run: |
          git add .
          git commit -m "Deploy documentation"
          git push origin gh-pages
