name: build

on: [ push, pull_request ]

jobs:

  build:

    name: build
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create txt file
        run: |
          mkdir docs
          cd docs
          echo Text > test.txt
          echo Sample > sample.txt
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: docs

  deploy:

    needs: build
    name: deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create orphan branch
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout --orphan gh-pages
          git pull origin gh-pages

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: docs

      - name: Commit to gh-pages branch
        run: |
          git add docs
          git commit -m "Deploy documentation"
          git push origin gh-pages

      - name: Create .nojekyll file
        run: echo > .nojekyll
